project:
  type: book

book:
  title: "Caribbean ESR Lab Report"
  author: "Carissa Gervasi"
  date: "2/6/2024"

  chapters:
    - part: "Part 1: Intro"
      chapters: 
        - index.qmd
    - part: "Part 2: Indicators"
      chapters:
        - OA.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: false
    output: false