project:
  type: book

book:
  title: "Ecosystem Status Report - Caribbean"
  author: "Carissa Gervasi"
  date: "2/6/2024"

  chapters:
    - index.qmd
    - Report_book_files/Report4.qmd

format:
  html:
    theme: flatly
    output: true
    echo: false
    number-sections: false
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: false
    toc: true
    lof: true
    lot: true
    titlepage: "bg-image"
    titlepage-bg-image: "_extensions/nmfs-opensci/titlepage/images/corner-bg.png"
    titlepage-logo: "_extensions/nmfs-opensci/titlepage/images/logo.png"
    titlepage-header: "The Publisher"
    titlepage-footer: |
      NOAA Fisheries OpenSci\
      Tools for Open Science\
      [https://github.com/nmfs-opensci](https://github.com/nmfs-opensci)\
    echo: false

editor: visual