# 3. Fishery management plan objectives and conceptual models

This report's indicator selection process sought to select indicators that corresponded to the island based fishery management plan (FMP) objectives in order to track performance, and also selected indicators related to risks to meeting these management objectives. The following figure shows indicators selected per FMP objective. Indicators were also sourced and considered from the conceptual model exercise completed by the Council's Science and Statistical Committee and District Advisory panels, which began in 2019. Top scored connections in ecosystem components were considered in the ESR indicator suite as well (Rivera et al, in publication).

| FMP Objective                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Col2                                                        | Col3                                                                                                                   | Col4 | Col5 | Col6 |
|-----------------------------|---------|---------|---------|---------|---------|
| Objective 1: Provide for long-term sustainable use of fisheries resources within the limits of local ecosystem production using a precautionary, ecosystem-based approach to management that accounts for uncertainty and relevant biological, ecological, economic, and social factors in the fishery, including the benefits of **food production**, **recreational opportunities, and protection of marine ecosystems**. **Prevent overfishing, rebuild overfished stocks, and achieve OY on a continuing basis.** | Total commercial landings, lobster landings, conch landings | Sustainability of economically important reef fish-FID from RVC on mutton, yellowtail, red hind, and queen triggerfish |      |      |      |
| Objective 2: Reduce bycatch and waste in the fishery.                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                             |                                                                                                                        |      |      |      |
| Objective 3: Ensure the metrics upon which OY is based are derived from the best available scientific information and are updated continuously every five years to respond to changing ecological, biological, economic, and social conditions.                                                                                                                                                                                                                                                                       |                                                             |                                                                                                                        |      |      |      |
| Objective 4: Promote international and domestic cooperation in the management of pan-Caribbean stocks.                                                                                                                                                                                                                                                                                                                                                                                                                |                                                             |                                                                                                                        |      |      |      |
| Objective 5: Minimize conflicts between stakeholders by promoting **effective marine spatial planning**                                                                                                                                                                                                                                                                                                                                                                                                               |                                                             |                                                                                                                        |      |      |      |
| Objective 6: Promote **fair and equitable use of fishery resources**, recognizing the importance of those resources to fishing communities within the context of differences in local environment, culture, markets, user groups, gears, and seafood preferences.                                                                                                                                                                                                                                                     |                                                             |                                                                                                                        |      |      |      |
| Objective 7: Establish resource access permits as necessary and appropriate to facilitate data collection, sustainability, and long-term yield.                                                                                                                                                                                                                                                                                                                                                                       |                                                             |                                                                                                                        |      |      |      |
| Objective 8: Provide flexibility in the management process which minimizes regulatory delay and allows for rapid adaptation to **changing resource abundance, availability, health, or preference**, using the best available scientific and socio-economic information.                                                                                                                                                                                                                                              |                                                             |                                                                                                                        |      |      |      |
| Objective 9: Devise a regulatory framework that maximizes the **efficiency and efficacy of enforcement efforts** within and across jurisdictional boundaries while promoting the safe conduct of fishing operations.                                                                                                                                                                                                                                                                                                  |                                                             |                                                                                                                        |      |      |      |
| Objective 10: Promote **awareness of laws and regulations governing marine resource management** and the science and social obligations that support that management, and to ensure informed public input into the management process.                                                                                                                                                                                                                                                                                |                                                             |                                                                                                                        |      |      |      |
| Objective 11: Ensure the **socioeconomic health of the fishing communities** dependent on federal fishery resources.                                                                                                                                                                                                                                                                                                                                                                                                  |                                                             |                                                                                                                        |      |      |      |
| Objective 12: **Protect spawning aggregations and, when needed, the habitats** supporting those aggregations to ensure the future health of the resource.                                                                                                                                                                                                                                                                                                                                                             |                                                             |                                                                                                                        |      |      |      |
| Objective 13: **Describe and identify EFH, adverse impacts on EFH, and other actions to conserve and enhance EFH**. Adopt management measures that minimize adverse impacts from fishing on EFH and promote habitat conservation, including designation of specific habitat areas of particular concern within EFH for more focused management action.                                                                                                                                                                |                                                             |                                                                                                                        |      |      |      |
| Objective 14: **Map, define, and manage habitat** upon which the resource depends, with particular emphasis on coral reef resources throughout the region.                                                                                                                                                                                                                                                                                                                                                            |                                                             |                                                                                                                        |      |      |      |
| Objective 15: Ensure **continued provision of ecosystem services derived from living marine resources**, including adequate abundance of forage resources to ensure a healthy and diverse trophic web.                                                                                                                                                                                                                                                                                                                |                                                             |                                                                                                                        |      |      |      |
| Objective 16: Account for **ecological relationships and functional roles of species in the fishery** that contribute to a healthy ecosystem, such as grazers, forage fish, habitat-builders, and top predators.                                                                                                                                                                                                                                                                                                      |                                                             |                                                                                                                        |      |      |      |
| Objective 17: Require essential scientific data is gathered and analyzed in advance to guide the development of new fisheries to ensure they are sustainable from the start.                                                                                                                                                                                                                                                                                                                                          |                                                             |                                                                                                                        |      |      |      |
| Objective 18: Promote measures to develop and sustainably manage underutilized marine fishery resources.                                                                                                                                                                                                                                                                                                                                                                                                              |                                                             |                                                                                                                        |      |      |      |
