# 2. Introduction

Ecosystem-based management of fisheries and other marine resources has emerged as a priority in the U.S. (EPAP 1999, Fluharty et al. 2006, McFadden and Barnes 2009, NOAA 2016) and elsewhere (Browman et al. 2004, Sainsbury et al. 2014, Walther and Möllmann 2014, Long et al. 2015). The NOAA National Marine Fisheries Service (NOAA Fisheries) defines ecosystem-based fisheries management (EBFM) as 'a systematic approach to fisheries management in a geographically specified area that contributes to the resilience and sustainability of the ecosystem; recognizes the physical, biological, economic, and social interactions among the affected fishery-related components of the ecosystem, including humans; and seeks to optimize benefits among a diverse set of societal goals' (NOAA 2016).

## 2.1 Indicator selection

This report relied on both previously identified proposed indicators as well as expert vetting to select a suite of indicators that best address the fishery management plan (FMP) objectives for the U.S. Caribbean. The CFMC's Science and Statistical Committee, as well as the region's Ecosystem-Based Fishery Management Technical Advisory Panel (EBFM TAP), recently completed a series of conceptual models linking key components of the ecosystem and human activities related to fishing. This report used these conceptual models as a starting list of proposed indicators and matched the indicators to answer FMP objectives when possible. For those objectives that did not have an immediate conceptual model-identified indicator, this report used a decision matrix process for expert vetting (Fig x).

insert fig

This decision matrix was composed of a list of proposed indicators compiled from the conceptual models as well as proposed indicators provided via expert input. These potential indicators were vetted and edited by expert small working groups, who then scored a decision matrix (Fig. x) of potential indicators against the following decision criteria: long term data availability, measurability, sensitivity to environmental changes, specificity, spatial and temporal scalability, relevance to specific FMP objectives, and responsiveness to management actions.

## 2.2 Notes on interpreting time series figures

Time series data are plotted in a standardized format for ease of interpretation (e.g., Fig. 2.1). The x-axis represents the temporal dimension, which may be monthly, yearly, or irregular time steps, and the y-axis represents the indicator value in units specified in the axis label. The dashed horizontal line represents the mean indicator value across the entire time series, and the solid horizontal lines denote the mean plus or minus one standard deviation. Red shaded areas and green shaded areas show years for which the indicator value is below or above one standard deviation from the mean, respectively. The blue vertical shaded box highlights the last five years of indicator values, over which additional metrics are calculated. Black circles to the right of each figure indicate whether the indicator values over the last five years are greater (plus sign), less than (minus sign), or within (solid circle) one standard deviation from the mean of the overall time series. Arrows to the right of each figure indicate whether the least squares linear fit through the last five years of data produces a positive or negative slope that is greater than one standard deviation (upward or downward arrows respectively), or less than one standard deviation (left-right arrow).
